version: '3'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: bday
      POSTGRES_USER: bday
      POSTGRES_DB: bday
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
